image:
  repository: trial5em87r.jfrog.io/flask-gitops-monitor-docker-local/flask-demo
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 256Mi

# # Optional
# imagePullSecrets:
#   - name: jfrog-pull-secret

